name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            echo "Starting Deployment..."
            
            # Navigate to the root folder
            cd /var/www/lms
            
            # Pull latest changes
            git reset --hard HEAD
            git pull origin main
            
            # Create frontend/.env.production to bake Next.js variables during build
            echo "NEXT_PUBLIC_API_URL=https://admin.mrhifnimuhammad.tech/api" > frontend/.env.production
            if grep -q "NEXT_PUBLIC_TURNSTILE_SITE_KEY" src/.env; then
                grep "NEXT_PUBLIC_TURNSTILE_SITE_KEY" src/.env >> frontend/.env.production
            fi
            
            # Rebuild and start any changed containers (Frontend & Backend)
            docker compose -f docker-compose.prod.yml build
            docker compose -f docker-compose.prod.yml up -d --build
            
            # Restart Nginx and Proxy to clear DNS cache and prevent 502 errors
            docker compose -f docker-compose.prod.yml restart nginx proxy
            
            # Clear caches and run migrations for Laravel
            docker exec lms_app php artisan.php optimize:clear
            docker exec lms_app php artisan.php migrate --force
            
            echo "Deployment Completed Successfully!"
