name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            echo "Starting Deployment..."
            
            # Navigate to the source folder and pull latest changes
            cd /var/www/lms/src
            git reset --hard HEAD
            git pull origin main
            
            # Navigate to the docker compose folder
            cd /var/www/lms
            
            # Clear caches and run migrations
            docker exec lms_app php artisan.php optimize:clear
            docker exec lms_app php artisan.php migrate --force
            
            # Restart Laravel containers to apply changes
            docker compose restart app queue scheduler
            
            echo "Deployment Completed Successfully!"
